package NS;

// ALGORITHM:

// STEP-1: Read the 128-bit plain text.
// STEP-2: Divide into four blocks of 32-bits named as A, B, C and D.

// STEP-3: Compute the functions f, g, h and i with operations such as, rotations, permutations, etc,.
// STEP-4: The output of these functions are combined together as F and performed circular shifting and then given to key round.
// STEP-5: Finally, right shift of ‘s’ times are performed and the results are combined together to produce the final output.

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

// Java program to calculate MD5 hash value
public class Ex2dMD5 {
    public static String getMd5(String input) {
        try {

            // Static getInstance method is called with hashing MD5
            MessageDigest md = MessageDigest.getInstance("MD5");

            // digest() method is called to calculate message digest
            // of an input digest() return array of byte
            byte[] messageDigest = md.digest(input.getBytes());

            // Convert byte array into signum representation
            BigInteger no = new BigInteger(1, messageDigest);

            // Convert message digest into hex value
            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }

        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    // Driver code
    public static void main(String args[]) throws NoSuchAlgorithmException {
        String s = "welcome to java";
        System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s));
    }
}

// OUTPUT
// Your HashCode Generated by MD5 is: ef7bc0d9fd0ff2489218753e8216f8ce